### PR TITLE
[settings] Add 'wacke.ow2.org' to ALLOWED_HOSTS

### PR DESCRIPTION
**Pull request by valeriocos**
This code extends the list of allowed hosts to include 'wacke.ow2.org'.

### CODE REVIEW

**Comment by valeriocos** [comment]
Hi @borisbaldassari ,

It could be an option. I'm going to check if it is possible to declare the `ALLOWED_HOSTS` using a file (this would simply the deployment for each partner).
According to the [documentation](https://docs.djangoproject.com/en/2.1/ref/settings/#allowed-hosts), it is possible (in your case it should be: `'.castalia.camp'`)

**Comment by mhow2** [comment]
hi @valeriocos , I just checked up this merge request. Thanks.
I think the best option would be to make possible to pass the variable to the docker container - `--env` option when you run `docker run`. Maybe it's already working ?

**Comment by valeriocos** [comment]
Thank you for the feedback @mhow2 . I have just updated it (I have still to run some tests).
Are the new changes aligned with what you suggested?

**Comment by borisbaldassari** [comment]
> hi @valeriocos , I just checked up this merge request. Thanks.
> I think the best option would be to make possible to pass the variable to the docker container - `--env` option when you run `docker run`. Maybe it's already working ?

That would be perfect regarding deployment's ease..

**Pull request merged**
